name: SyncCommand
version: ${project.version}
api-version: 1.20
main: org.me.synccommand.bukkit.SyncCommandBukkit
author: TonyPak
folia-support: true
commands:
  sync:
    description: Allows the user to synchronize a command across multiple servers.
    permission: sync.sync
permissions:
    synccommand.sync:
        default: op
