name: SyncCommand
version: ${project.version}
api-version: 1.19
main: org.me.synccommand.bukkit.SyncCommandBukkit
author: kit8379
folia-support: true
commands:
  sync:
    description: Allows the user to synchronize a command across multiple servers.
    usage: /<command>
    permission: synccommand.admin
  syncreload:
    description: Reloads the SyncCommand plugin
    usage: /<command>
    permission: synccommand.admin
permissions:
    synccommand.admin:
        default: op
