name: SyncCommand
version: ${plugin.version}
api-version: 1.20
main: org.me.synccommand.bukkit.SyncCommandBukkit
author: TonyPak
commands:
  sync:
    description: Allows the user to synchronize a command across multiple servers.
    permission: sync.sync
permissions:
    sync.sync:
        default: op
